### PR TITLE
Fix regexp to handle datetime lines starting wih a few characters before `On...`

### LINKED ISSUE #77: EmailReplyParser::parseReply issue
Hello,

I just got a bug on `EmailReplyParser::parseReply`. In some specific case, the reply is truncated in the middle.

I tried to reduce at maximum a case, here it is : 

```
Bonjour ​Test​,

​Text paragraph 1​


Le paragraphe qui pose problème.

​Text paragraph 2​


- Le 2021-04-09 23:25, ​Test a écrit :
``` 

The correct result should be : 

```
Bonjour ​Test​,

​Text paragraph 1​


Le paragraphe qui pose problème.

​Text paragraph 2​
```

The current result is : 
```
Bonjour ​Test​,

        ​Text paragraph 1​
```

Context : 
* This is french. If I remove the first "Le" : problem solved. If I remove "écrit" : problem solved.
* `Le paragraphe qui pose problème` means `The paragraph which provoke issue`. 
* `Le 2021-04-09 23:25, ​Test a écrit :` means `On 2021-04-09 23:25, ​Test wrote :`

So the issue is here : 
```
'/^\s*(Le(?:(?!^>*\s*Le\b|\bécrit:).){0,1000}écrit(\s|\xc2\xa0):)$/ms', // Le DATE, NAME <EMAIL> a écrit :
```

If I change it to have the same format as the english work : problem half solved (not truncated).
```
'/^\s*(Le(?:(?!^>*\s*Le\b|\bécrit:).){0,1000}écrit:)$/ms', // Le DATE, NAME <EMAIL> a écrit :
```

But I think that `(\s|\xc2\xa0)` was here for some reason ? @Spone ?

see also : 
https://github.com/willdurand/EmailReplyParser/commit/e888d795f277916ec62c2e812b9a10a9614682e8#diff-5e5f4da6cc02b271ae11752a0b5e45ecb842d913728f7b7d9756d88d9219a0f8
https://github.com/willdurand/EmailReplyParser/commit/b71d9983c07b0455cb5b9727b90642a32bc11ae0#diff-5e5f4da6cc02b271ae11752a0b5e45ecb842d913728f7b7d9756d88d9219a0f8

### PR DESCRIPTION
**Pull request by Nuranto**
This fixes #77 

The rule is more permissive for prefixes, however more strict and secure as I disabled the `s` modifier which allowed multiline for some reason.

Important Note : I only fixed FR. I prepared (commented) a failing test for EN, which failed. But if I do the same change for EN regexp, other tests are failing and I don't want to mess up things, so I'll let you have a look at this.

### CODE REVIEW

**Comment by willdurand** [comment]
> Important Note : I only fixed FR. I prepared (commented) a failing test for EN, which failed. But if I do the same change for EN regexp, other tests are failing and I don't want to mess up things, so I'll let you have a look at this.

That seems safer to me anyway, thanks.

File: tests/EmailReplyParser/Tests/Parser/EmailParserTest.php [hunk 1]
```diff
@@ -273,6 +273,22 @@ public function testEmailGmailNo()
...
 
+    public function testEmailFreeZimbraFr()
+    {
+        $email     = $this->parser->parse($this->getFixtures('email_zimbra_free_fr.txt'));
+        $fragments = $email->getFragments();
+        $this->assertStringContainsString('Michael Scott', $fragments[0]);
+        $this->assertStringNotContainsString('Toby Flenderson', $fragments[0]);
+    }
+
+    /*public function testEmailFreeZimbraEn()
```
Comment (willdurand) [inline tests/EmailReplyParser/Tests/Parser/EmailParserTest.php:284]: Please remove this. We don't need commented code.

File: src/EmailReplyParser/Parser/EmailParser.php [hunk 2]
```diff
@@ -32,7 +32,7 @@ class EmailParser
      */
     private $quoteHeadersRegex = array(
         '/^\s*(On(?:(?!^>*\s*On\b|\bwrote:).){0,1000}wrote:)$/ms', // On DATE, NAME <EMAIL> wrote:
-        '/^\s*(Le(?:(?!^>*\s*Le\b|\bécrit:).){0,1000}écrit(\s|\xc2\xa0):)$/ms', // Le DATE, NAME <EMAIL> a écrit :
+        '/^.{0,5}(Le\b(?:(?!^>*\s*Le\b|\bécrit(\s|\xc2\xa0)?:).){0,1000}écrit(\s|\xc2\xa0)?:)$/m', // Le DATE, NAME <EMAIL> a écrit :
```
Comment (willdurand) [inline src/EmailReplyParser/Parser/EmailParser.php:35]: So you dropped the `s` modifier here. Was it intended?

**Review by willdurand — CHANGES_REQUESTED** [review]

File: tests/EmailReplyParser/Tests/Parser/EmailParserTest.php (hunk 1 above)
Comment (Nuranto) [reply tests/EmailReplyParser/Tests/Parser/EmailParserTest.php:284]: I just commented it because it fails, so I think it should be uncommented and the regex should be fixed. In current state, that kind of email is wrongly parsed, and data can be lost.
But as I said, I don't understand all EN tests and rules, so I didn't want to do it myself. However, I can remove this indeed, I don't have EN users anyway.

Comment (willdurand) [reply tests/EmailReplyParser/Tests/Parser/EmailParserTest.php:284]: Well, unless you find a way to fix the regex without breaking other test cases, I don't think it's very useful to keep a commented test case.

**Comment by Nuranto** [comment]
OK @willdurand 

I saw `email_6.txt` example, and understand better the goal of the `s`. So I found another solution, based on the subpattern exclusion rule. I think it's better, and it works for EN as well. 
I modified in the same spirit IT and ES rules.

All tests passed.

I suggest to squash commits when/if merging, it will be nicer :)

**Comment by Nuranto** [comment]
Hello @willdurand 

Do you need me to do something else so we can merge this ?

**Comment by willdurand** [comment]
> Do you need me to do something else so we can merge this ?

Nope, thanks!
